# Generated by Django 4.2.5 on 2023-09-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=20)),
                ('producer', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('num', models.CharField(max_length=20)),
            ],
        ),
    ]
